Repository keqi000/proyek-pengembangan-web-berbasis-framework-terbaru, pull requests merged in 2025-04, with the labels that each got.

#35 fix: Fix nonexistent route at user page
  src/app/user/_component/Footer.tsx
  src/app/user/layout.tsx
Labels: enhancement

#39 feat: Add linting and build check when push and pull request
  .github/workflows/pull-request.yml
Labels: enhancement

#40 cleanup: fix lint issue
  src/app/admin/_store/jadwal.ts
  src/app/admin/generate_schedule/page.tsx
  src/app/admin/lecturers/page.tsx
  src/app/admin/manage_subject/page.tsx
  src/app/admin/rooms/page.tsx
  src/app/signin/page.tsx
  src/app/user/_component/navbar.tsx
  src/app/user/cetak_jadwal/page.tsx
  src/app/user/schedule/page.tsx
Labels: bug

#41 fix: Remove build ci in lint workflow
  .github/workflows/pull-request.yml
Labels: bug

#38 buat halaman help
  package-lock.json
  package.json
  src/app/admin/admin_component/accordion.tsx
  src/app/admin/admin_component/card.tsx
  src/app/admin/admin_component/tabs.tsx
  src/app/admin/help/page.tsx
  src/app/admin/lib/utils.ts
Labels: enhancement

#44 cleanup: fix lint issue from previous commit
  src/app/admin/settings/page.tsx
Labels: bug

#42 cleanup: Set type declaration based on zod schema
  src/app/admin/_scheme/course.ts
  src/app/admin/_scheme/lecturers.ts
  src/app/admin/_scheme/room.ts
  src/app/admin/lecturers/page.tsx
  src/app/admin/manage_subject/page.tsx
  src/app/admin/rooms/page.tsx
Labels: enhancement

#45 fix: fix the layout to ensure the logout button appeared when scrolling
  src/app/admin/admin_component/Navbar.tsx
Labels: bug

#46 fix: fix input color
  src/app/admin/manage_subject/page.tsx
  src/app/admin/rooms/page.tsx
  src/app/admin/settings/page.tsx
Labels: bug

#47 fix: fix search input layout
  src/app/admin/lecturers/page.tsx
  src/app/admin/manage_subject/page.tsx
  src/app/admin/rooms/page.tsx
Labels: enhancement

#49 fix: fix sign-in responsive in mobile layout
  src/app/signin/page.tsx
Labels: bug

#50 fix: fix sign-up mobile responsive
  src/app/page.tsx
Labels: bug

#52 update cetak jadwal
  package-lock.json
  package.json
  src/app/user/cetak_jadwal/page.tsx
Labels: bug

#53 updata halaman matakuliah dan generate schedule
  src/app/admin/generate_schedule/page.tsx
  src/app/admin/manage_subject/page.tsx
Labels: enhancement

#54 cleanup: Delete unused error pages
  src/app/admin/produk/[id]/page.tsx
  src/app/admin/produk/not-found.tsx
  src/app/admin/test-error/page.tsx
Labels: enhancement

#48 fix: fix generate schedule layout in desktop
  src/app/admin/generate_schedule/page.tsx
Labels: bug

#55 chore: Set dedicated sign-up route
  src/app/page.tsx
  src/app/signup/page.tsx
Labels: enhancement

#56 mengubah grid admin
  src/app/admin/manage_subject/page.tsx
  src/app/admin/rooms/page.tsx
Labels: bug

#57 fix: fix the position of hamburger menu and profile icon
  src/app/admin/layout.tsx
Labels: bug

#59 fix: set smaller font in GeneralJadwal's table
  src/app/admin/generate_schedule/page.tsx
Labels: bug

#60 documentation: Add about the app and how to build app
  README.md
Labels: documentation, enhancement

#62 tambah halaman notifikasi dan juga layout notifikasi
  src/app/admin/admin_component/Navbar.tsx
  src/app/admin/layout.tsx
  src/app/admin/notifications/page.tsx
Labels: enhancement

#64 update modal delete di admin
  src/app/admin/generate_schedule/page.tsx
  src/app/admin/lecturers/page.tsx
  src/app/admin/manage_subject/page.tsx
  src/app/admin/rooms/page.tsx
Labels: enhancement
